apiVersion: v1
kind: Pod
metadata:
  name: nodeapp-pod
  labels:
    app: nodeapp
spec:
  containers:
  - name: nodeapp
    image: gcr.io/delta-avenue-396214/nodeapp:950dcdf
    ports:
    - containerPort: 3000
